<?php

namespace Database\Seeders;

use App\Models\Factor;
use App\Models\Question;
use Illuminate\Database\Seeder;

class QuestionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Forward/Backward Questions
        $questions = [
            [
                'label' => 'Time seems to be passing faster than when I was younger.',
                'label_pl' => 'Wydaje mi się, że czas płynie szybciej niż wtedy, gdy byłem młodszy.',
                'label_de' => 'Die Zeit scheint schneller zu vergehen als damals, als ich jünger war.',
                'label_pt' => 'O tempo parece estar passando mais rápido do que quando eu era mais jovem.',
                'label_es' => 'El tiempo parece pasar más rápido que cuando era más joven.',
                'label_fr' => 'Le temps semble passer plus vite que lorsque j’étais plus jeune.',
                'label_it' => 'Il tempo sembra passare più velocemente di quando ero più giovane.',
                'mode' => 'backward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question1_answer_id',
            ],
            [
                'label' => 'Most of my family and friends appreciate who I am.',
                'label_pl' => 'Większość mojej rodziny i przyjaciół docenia to, kim jestem.',
                'label_de' => 'Die meisten meiner Familie und Freunde schätzen mich.',
                'label_pt' => 'A maioria da minha família e amigos apreciam quem eu sou.',
                'label_es' => 'La mayoría de mi familia y amigos me aprecian.',
                'label_fr' => "La plupart de ma famille et de mes amis m'apprécient.",
                'label_it' => 'La maggior parte della mia famiglia e dei miei amici mi apprezza.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question2_answer_id',
            ],
            [
                'label' => 'I seldom think about my retirement.',
                'label_pl' => 'Rzadko myślę o swojej emeryturze.',
                'label_de' => 'Ich denke selten an meinen Ruhestand.',
                'label_pt' => 'Raramente penso na minha aposentadoria.',
                'label_es' => 'Rara vez pienso en mi jubilación.',
                'label_fr' => 'Je pense rarement à ma retraite.',
                'label_it' => 'Raramente penso alla mia pensione.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question3_answer_id',
            ],
            [
                'label' => 'I have forgiven all the people that have hurt me deeply.',
                'label_pl' => 'Wybaczyłam wszystkim ludziom, którzy mnie głęboko zranili.',
                'label_de' => 'Ich habe allen Menschen vergeben, die mich zutiefst verletzt haben.',
                'label_pt' => 'Eu perdoei todas as pessoas que me magoaram profundamente.',
                'label_es' => 'He perdonado a todos los que me lastimaron profundamente.',
                'label_fr' => "J'ai pardonné à tous ceux qui m'ont profondément blessé.",
                'label_it' => 'Ho perdonato tutti coloro che mi hanno ferito profondamente.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Generosity',
                'answers_ref_column' => 'question4_answer_id',
            ],
            [
                'label' => 'I look forward to creating an exciting future for myself.',
                'label_pl' => 'Nie mogę się doczekać, aby stworzyć dla siebie ekscytującą przyszłość.',
                'label_de' => 'Ich freue mich darauf, eine spannende Zukunft für mich zu gestalten.',
                'label_pt' => 'Estou ansioso para criar um futuro emocionante para mim.',
                'label_es' => 'Espero crear un futuro emocionante para mí.',
                'label_fr' => 'J’ai hâte de me créer un avenir passionnant.',
                'label_it' => 'Non vedo l’ora di creare un futuro entusiasmante per me stesso.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question5_answer_id',
            ],
            [
                'label' => 'Genetics is not the most important factor in longevity.',
                'label_pl' => 'Genetyka nie jest najważniejszym czynnikiem wpływającym na długowieczność.',
                'label_de' => 'Genetik ist nicht der wichtigste Faktor für Langlebigkeit.',
                'label_pt' => 'A genética não é o fator mais importante na longevidade.',
                'label_es' => 'La genética no es el factor más importante en la longevidad.',
                'label_fr' => "La génétique n'est pas le facteur le plus important de la longévité.",
                'label_it' => 'La genetica non è il fattore più importante per la longevità.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question6_answer_id',
            ],
            [
                'label' => 'I am as healthy as I was ten years ago.',
                'label_pl' => 'Jestem tak zdrowy jak dziesięć lat temu.',
                'label_de' => 'Ich bin so gesund wie vor zehn Jahren.',
                'label_pt' => 'Estou tão saudável quanto estava há dez anos.',
                'label_es' => 'Estoy tan sano como hace diez años.',
                'label_fr' => "Je suis aussi en bonne santé qu'il y a dix ans.",
                'label_it' => 'Sono sano come lo ero dieci anni fa.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question7_answer_id',
            ],
            [
                'label' => 'It’s easy for me to shift from work to play mode.',
                'label_pl' => 'Dla mnie łatwo jest przejść z trybu pracy na tryb zabawy.',
                'label_de' => 'Es ist für mich einfach, vom Arbeits- in den Spielmodus zu wechseln.',
                'label_pt' => 'Para mim é fácil mudar do modo de trabalho para o modo de diversão.',
                'label_es' => 'Para mí es fácil cambiar del modo trabajo al modo juego.',
                'label_fr' => 'Il est facile pour moi de passer du mode travail au mode jeu.',
                'label_it' => 'È facile per me passare dalla modalità lavoro alla modalità gioco.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question8_answer_id',
            ],
            [
                'label' => 'I always find time to do kind things for myself.',
                'label_pl' => 'Zawsze znajduję czas, aby zrobić dla siebie miłe rzeczy.',
                'label_de' => 'Ich finde immer Zeit, um nette Dinge für mich zu tun.',
                'label_pt' => 'Sempre encontro tempo para fazer coisas boas para mim mesmo.',
                'label_es' => 'Siempre encuentro tiempo para hacer cosas amables para mí mismo.',
                'label_fr' => 'Je trouve toujours le temps de faire des choses gentilles pour moi-même.',
                'label_it' => 'Trovo sempre il tempo per fare cose gentili per me stesso.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question9_answer_id',
            ],
            [
                'label' => 'I love to explore new places.',
                'label_pl' => 'Uwielbiam odkrywać nowe miejsca.',
                'label_de' => 'Ich liebe es, neue Orte zu erkunden.',
                'label_pt' => 'Adoro explorar novos lugares.',
                'label_es' => 'Me encanta explorar nuevos lugares.',
                'label_fr' => "J'adore explorer de nouveaux endroits.",
                'label_it' => 'Amo esplorare nuovi posti.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question10_answer_id',
            ],
            [
                'label' => 'People that know me think I am attractive.',
                'label_pl' => 'Ludzie, którzy mnie znają, uważają, że jestem atrakcyjny/a.',
                'label_de' => 'Menschen, die mich kennen, finden mich attraktiv.',
                'label_pt' => 'As pessoas que me conhecem acham-me atraente.',
                'label_es' => 'Las personas que me conocen piensan que soy atractivo/a.',
                'label_fr' => 'Les gens qui me connaissent pensent que je suis attirant/e.',
                'label_it' => 'Le persone che mi conoscono pensano che io sia attraente.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question11_answer_id',
            ],
            [
                'label' => 'Mondays are creative days for me.',
                'label_pl' => 'Poniedziałki są dla mnie dniem kreatywnym.',
                'label_de' => 'Montage sind für mich kreative Tage.',
                'label_pt' => 'Segundas-feiras são dias criativos para mim.',
                'label_es' => 'Los lunes son días creativos para mí.',
                'label_fr' => 'Les lundis sont des jours créatifs pour moi.',
                'label_it' => 'I lunedì sono giorni creativi per me.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question12_answer_id',
            ],
            [
                'label' => 'I am healthier than most of my family members.',
                'label_pl' => 'Jestem zdrowszy/a niż większość moich członków rodziny.',
                'label_de' => 'Ich bin gesünder als die meisten meiner Familienmitglieder.',
                'label_pt' => 'Sou mais saudável do que a maioria dos membros da minha família.',
                'label_es' => 'Soy más saludable que la mayoría de los miembros de mi familia.',
                'label_fr' => 'Je suis en meilleure santé que la plupart de mes membres de famille.',
                'label_it' => 'Sono più sano/a della maggior parte dei membri della mia famiglia.',
                'mode' => 'forward',
                'factor1' => 'Health',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question13_answer_id',
            ],
            [
                'label' => 'I am good at confronting my physical limitations.',
                'label_pl' => 'Jestem dobry/a w konfrontowaniu moich fizycznych ograniczeń.',
                'label_de' => 'Ich bin gut darin, meine körperlichen Grenzen zu überwinden.',
                'label_pt' => 'Sou bom/buena a enfrentar as minhas limitações físicas.',
                'label_es' => 'Soy bueno/a enfrentando mis limitaciones físicas.',
                'label_fr' => 'Je suis bon/bonne pour affronter mes limites physiques.',
                'label_it' => 'Sono bravo/a ad affrontare le mie limitazioni fisiche.',
                'mode' => 'forward',
                'factor1' => 'Health',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question14_answer_id',
            ],
            [
                'label' => 'I can influence my future.',
                'label_pl' => 'Mogę wpływać na swoją przyszłość.',
                'label_de' => 'Ich kann meine Zukunft beeinflussen.',
                'label_pt' => 'Posso influenciar o meu futuro.',
                'label_es' => 'Puedo influir en mi futuro.',
                'label_fr' => 'Je peux influencer mon avenir.',
                'label_it' => 'Posso influenzare il mio futuro.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question15_answer_id',
            ],
            [
                'label' => 'Other people tell me I look younger than my chronological age.',
                'label_pl' => 'Inni ludzie mówią mi, że wyglądam młodziej niż wynika to z mojego wieku.',
                'label_de' => 'Andere Leute sagen mir, dass ich jünger aussehe als mein chronologisches Alter.',
                'label_pt' => 'Outras pessoas dizem que pareço mais jovem do que a minha idade cronológica.',
                'label_es' => 'Otras personas me dicen que parezco más joven que mi edad cronológica.',
                'label_fr' => 'Les autres me disent que je parais plus jeune que mon âge chronologique.',
                'label_it' => 'Altre persone mi dicono che sembro più giovane della mia età cronologica.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question16_answer_id',
            ],
            [
                'label' => 'My personal views of the world can affect my health.',
                'label_pl' => 'Moje osobiste poglądy na świat mogą wpływać na moje zdrowie.',
                'label_de' => 'Meine persönlichen Ansichten über die Welt können meine Gesundheit beeinflussen.',
                'label_pt' => 'Minhas opiniões pessoais sobre o mundo podem afetar minha saúde.',
                'label_es' => 'Mis puntos de vista personales sobre el mundo pueden afectar mi salud.',
                'label_fr' => 'Mes opinions personnelles sur le monde peuvent affecter ma santé.',
                'label_it' => 'Le mie opinioni personali sul mondo possono influenzare la mia salute.',
                'mode' => 'forward',
                'factor1' => 'Health',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question17_answer_id',
            ],
            [
                'label' => 'Longevity is mostly influenced by family genetics.',
                'label_pl' => 'Długowieczność jest głównie determinowana genetyką rodziną.',
                'label_de' => 'Die Langlebigkeit wird hauptsächlich von der Familiengenetik beeinflusst.',
                'label_pt' => 'A longevidade é principalmente influenciada pela genética familiar.',
                'label_es' => 'La longevidad está mayormente influenciada por la genética familiar.',
                'label_fr' => 'La longévité est principalement influencée par la génétique familiale.',
                'label_it' => 'La longevità è principalmente influenzata dalla genetica familiare.',
                'mode' => 'backward',
                'factor1' => 'Health',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question18_answer_id',
            ],
            [
                'label' => 'My friends think I have a good sense of humor.',
                'label_pl' => 'Moim przyjaciołom wydaje się, że mam dobry zmysł humoru.',
                'label_de' => 'Meine Freunde denken, dass ich einen guten Sinn für Humor habe.',
                'label_pt' => 'Meus amigos acham que eu tenho um bom senso de humor.',
                'label_es' => 'Mis amigos piensan que tengo un buen sentido del humor.',
                'label_fr' => "Mes amis pensent que j'ai un bon sens de l'humour.",
                'label_it' => "I miei amici pensano che io abbia un buon senso dell'umorismo.",
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question19_answer_id',
            ],
            [
                'label' => 'I can fall in love again at any age.',
                'label_pl' => 'Mogę się ponownie zakochać w każdym wieku.',
                'label_de' => 'Ich kann mich in jedem Alter wieder verlieben.',
                'label_pt' => 'Posso me apaixonar novamente em qualquer idade.',
                'label_es' => 'Puedo enamorarme de nuevo a cualquier edad.',
                'label_fr' => "Je peux tomber amoureux à nouveau à n'importe quel âge.",
                'label_it' => 'Posso innamorarmi di nuovo a qualsiasi età.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Generosity',
                'answers_ref_column' => 'question20_answer_id',
            ],
            [
                'label' => 'I face adversity with curiosity more than with fear.',
                'label_pl' => 'Stawiam czoła przeciwnościom z ciekawością bardziej niż ze strachem.',
                'label_de' => 'Ich begegne Widrigkeiten eher mit Neugier als mit Angst.',
                'label_pt' => 'Enfrento adversidades com curiosidade mais do que com medo.',
                'label_es' => 'Enfrento la adversidad con curiosidad más que con miedo.',
                'label_fr' => "Je fais face à l'adversité avec curiosité plus qu'avec peur.",
                'label_it' => "Affronto l'avversità con curiosità più che con paura.",
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question21_answer_id',
            ],
            [
                'label' => 'Good fortune is my nature.',
                'label_pl' => 'Dobra fortuna jest moją naturą.',
                'label_de' => 'Das Glück ist meine Natur.',
                'label_pt' => 'A boa sorte é minha natureza.',
                'label_es' => 'La buena fortuna es mi naturaleza.',
                'label_fr' => 'La bonne fortune est ma nature.',
                'label_it' => 'La fortuna è la mia natura.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question22_answer_id',
            ],
            [
                'label' => 'I identify with my work more than with my leisure time.',
                'label_pl' => 'Identyfikuję się z moją pracą bardziej niż z moim czasem wolnym.',
                'label_de' => 'Ich identifiziere mich mehr mit meiner Arbeit als mit meiner Freizeit.',
                'label_pt' => 'Identifico-me mais com o meu trabalho do que com o meu tempo de lazer.',
                'label_es' => 'Me identifico más con mi trabajo que con mi tiempo de ocio.',
                'label_fr' => "Je m'identifie davantage à mon travail qu'à mon temps libre.",
                'label_it' => 'Mi identifico di più con il mio lavoro che con il mio tempo libero.',
                'mode' => 'backward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question23_answer_id',
            ],
            [
                'label' => 'Bad people cannot help how they behave because of their genetics.',
                'label_pl' => 'Źli ludzie nie mogą kontrolować swojego zachowania ze względu na swoją genetykę.',
                'label_de' => 'Schlechte Menschen können nicht kontrollieren, wie sie sich aufgrund ihrer Genetik verhalten.',
                'label_pt' => 'Pessoas más não podem controlar seu comportamento por causa de sua genética.',
                'label_es' => 'Las personas malas no pueden controlar cómo se comportan debido a su genética.',
                'label_fr' => 'Les mauvaises personnes ne peuvent pas contrôler leur comportement en raison de leur génétique.',
                'label_it' => 'Le persone cattive non possono controllare il loro comportamento a causa della loro genetica.',
                'mode' => 'backward',
                'factor1' => 'Health',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question24_answer_id',
            ],
            [
                'label' => 'I rely more on my doctor than myself when I am sick.',
                'label_pl' => 'W czasie choroby polegam bardziej na moim lekarzu niż na sobie.',
                'label_de' => 'Wenn ich krank bin, verlasse ich mich mehr auf meinen Arzt als auf mich selbst.',
                'label_pt' => 'Quando estou doente, confio mais no meu médico do que em mim mesmo.',
                'label_es' => 'Cuando estoy enfermo, confío más en mi médico que en mí mismo.',
                'label_fr' => "Quand je suis malade, je fais plus confiance à mon médecin qu'à moi-même.",
                'label_it' => 'Quando sono malato, mi affido più al mio medico che a me stesso.',
                'mode' => 'backward',
                'factor1' => 'Health',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question25_answer_id',
            ],
            [
                'label' => 'I can explore other careers when I retire from my job.',
                'label_pl' => 'Mogę eksplorować inne ścieżki kariery po przejściu na emeryturę.',
                'label_de' => 'Ich kann andere Karrieren erkunden, wenn ich in Rente gehe.',
                'label_pt' => 'Posso explorar outras carreiras quando me aposentar do meu trabalho.',
                'label_es' => 'Puedo explorar otras carreras cuando me retire de mi trabajo.',
                'label_fr' => "Je peux explorer d'autres carrières lorsque je prends ma retraite.",
                'label_it' => 'Posso esplorare altre carriere quando andrò in pensione.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question26_answer_id',
            ],
            [
                'label' => 'I would love to reach 100 years of age to see new inventions and discoveries.',
                'label_pl' => 'Chciałbym dożyć 100 lat, aby zobaczyć nowe wynalazki i odkrycia.',
                'label_de' => 'Ich würde gerne 100 Jahre alt werden, um neue Erfindungen und Entdeckungen zu sehen.',
                'label_pt' => 'Eu adoraria alcançar os 100 anos de idade para ver novas invenções e descobertas.',
                'label_es' => 'Me encantaría llegar a los 100 años para ver nuevas invenciones y descubrimientos.',
                'label_fr' => "J'aimerais atteindre l'âge de 100 ans pour voir de nouvelles inventions et découvertes.",
                'label_it' => 'Mi piacerebbe raggiungere i 100 anni per vedere nuove invenzioni e scoperte.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question27_answer_id',
            ],
            [
                'label' => 'Sharing meals with family and friends is very important in my life.',
                'label_pl' => 'Dzielenie się posiłkami z rodziną i przyjaciółmi jest bardzo ważne w moim życiu.',
                'label_de' => 'Das Teilen von Mahlzeiten mit Familie und Freunden ist sehr wichtig in meinem Leben.',
                'label_pt' => 'Compartilhar refeições com a família e amigos é muito importante na minha vida.',
                'label_es' => 'Compartir comidas con la familia y amigos es muy importante en mi vida.',
                'label_fr' => 'Partager des repas avec la famille et les amis est très important dans ma vie.',
                'label_it' => 'Condividere i pasti con la famiglia e gli amici è molto importante nella mia vita.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Generosity',
                'answers_ref_column' => 'question28_answer_id',
            ],
            [
                'label' => 'I make time for myself to enjoy my own company.',
                'label_pl' => 'Znajduję czas dla siebie, aby cieszyć się własnym towarzystwem.',
                'label_de' => 'Ich nehme mir Zeit für mich, um meine eigene Gesellschaft zu genießen.',
                'label_pt' => 'Dedico tempo para desfrutar da minha própria companhia.',
                'label_es' => 'Me dedico tiempo para disfrutar de mi propia compañía.',
                'label_fr' => 'Je prends du temps pour moi pour apprécier ma propre compagnie.',
                'label_it' => 'Mi faccio del tempo per godermi la mia compagnia.',
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question29_answer_id',
            ],
            [
                'label' => 'My eating habits are better than when I was younger.',
                'label_pl' => 'Moje nawyki żywieniowe są lepsze niż w młodości.',
                'label_de' => 'Meine Essgewohnheiten sind besser als in meiner Jugend.',
                'label_pt' => 'Meus hábitos alimentares são melhores do que quando eu era mais jovem.',
                'label_es' => 'Mis hábitos alimenticios son mejores que cuando era más joven.',
                'label_fr' => "Mes habitudes alimentaires sont meilleures que lorsque j'étais plus jeune.",
                'label_it' => 'Le mie abitudini alimentari sono migliori rispetto a quando ero più giovane.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question30_answer_id',
            ],
            [
                'label' => 'My best years are ahead.',
                'label_pl' => 'Moje najlepsze lata są jeszcze przede mną.',
                'label_de' => 'Meine besten Jahre liegen noch vor mir.',
                'label_pt' => 'Os meus melhores anos estão à frente.',
                'label_es' => 'Mis mejores años están por delante.',
                'label_fr' => 'Mes meilleures années sont à venir.',
                'label_it' => 'I miei anni migliori sono davanti a me.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question31_answer_id',
            ],
            [
                'label' => 'My family believe I am intelligent.',
                'label_pl' => 'Moja rodzina uważa, że jestem inteligentny.',
                'label_de' => 'Meine Familie glaubt, dass ich intelligent bin.',
                'label_pt' => 'Minha família acredita que sou inteligente.',
                'label_es' => 'Mi familia cree que soy inteligente.',
                'label_fr' => 'Ma famille croit que je suis intelligent.',
                'label_it' => 'La mia famiglia crede che io sia intelligente.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question32_answer_id',
            ],
            [
                'label' => 'I live in my past more than my present.',
                'label_pl' => 'Żyję bardziej w przeszłości niż teraźniejszości.',
                'label_de' => 'Ich lebe mehr in meiner Vergangenheit als in meiner Gegenwart.',
                'label_pt' => 'Eu vivo mais no meu passado do que no presente.',
                'label_es' => 'Vivo más en mi pasado que en mi presente.',
                'label_fr' => 'Je vis plus dans mon passé que dans mon présent.',
                'label_it' => 'Vivo più nel mio passato che nel mio presente.',
                'mode' => 'backward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question33_answer_id',
            ],
            [
                'label' => 'When I make up my mind to do what I believe is best for me, I do not need approval from important people in my life.',
                'label_pl' => 'Kiedy zdecyduję się na to, co uważam za najlepsze dla siebie, nie potrzebuję aprobaty ważnych osób w moim życiu.',
                'label_de' => 'Wenn ich mich entscheide, das zu tun, was ich für das Beste für mich halte, brauche ich keine Zustimmung von wichtigen Personen in meinem Leben.',
                'label_pt' => 'Quando decido fazer o que acredito ser o melhor para mim, não preciso de aprovação de pessoas importantes na minha vida.',
                'label_es' => 'Cuando decido hacer lo que creo que es mejor para mí, no necesito la aprobación de personas importantes en mi vida.',
                'label_fr' => "Quand je décide de faire ce que je crois être le meilleur pour moi, je n'ai pas besoin de l'approbation des personnes importantes dans ma vie.",
                'label_it' => "Quando decido fare ciò che credo sia meglio per me, non ho bisogno dell'approvazione delle persone importanti nella mia vita.",
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question34_answer_id',
            ],
            [
                'label' => 'I see uncertainty as opportunities to learn about myself.',
                'label_pl' => 'Postrzegam niepewność jako możliwości nauki o sobie.',
                'label_de' => 'Ich betrachte Unsicherheit als Gelegenheiten, um über mich selbst zu lernen.',
                'label_pt' => 'Vejo a incerteza como oportunidades para aprender sobre mim mesmo.',
                'label_es' => 'Veo la incertidumbre como oportunidades para aprender sobre mí mismo.',
                'label_fr' => "Je vois l'incertitude comme des opportunités pour apprendre sur moi-même.",
                'label_it' => "Vedo l'incertezza come opportunità per imparare su di me.",
                'mode' => 'forward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question35_answer_id',
            ],
            [
                'label' => 'No matter how hard I try, others do not recognize my achievements.',
                'label_pl' => 'Niezależnie od tego, jak bardzo się staram, inni nie doceniają moich osiągnięć.',
                'label_de' => 'Egal wie sehr ich mich anstrenge, andere erkennen meine Leistungen nicht an.',
                'label_pt' => 'Por mais que eu tente, os outros não reconhecem as minhas conquistas.',
                'label_es' => 'No importa cuánto lo intente, otros no reconocen mis logros.',
                'label_fr' => 'Peu importe mes efforts, les autres ne reconnaissent pas mes réalisations.',
                'label_it' => 'Non importa quanto ci provi, gli altri non riconoscono i miei successi.',
                'mode' => 'backward',
                'factor1' => 'Time',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question36_answer_id',
            ],
            [
                'label' => 'Most of the misfortunes in life are because of bad luck.',
                'label_pl' => 'Większość nieszczęść w życiu wynika z pecha.',
                'label_de' => 'Die meisten Missgeschicke im Leben passieren aufgrund von Pech.',
                'label_pt' => 'A maioria das desventuras na vida acontece por causa do azar.',
                'label_es' => 'La mayoría de los infortunios en la vida son debido a la mala suerte.',
                'label_fr' => 'La plupart des malheurs dans la vie sont dus à la malchance.',
                'label_it' => 'La maggior parte delle sfortune nella vita è dovuta alla sfortuna.',
                'mode' => 'backward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question37_answer_id',
            ],
            [
                'label' => 'In general, I love others more than they love me.',
                'label_pl' => 'Generalnie kocham innych bardziej niż oni mnie kochają.',
                'label_de' => 'Im Allgemeinen liebe ich andere mehr als sie mich lieben.',
                'label_pt' => 'No geral, eu amo os outros mais do que eles me amam.',
                'label_es' => 'En general, quiero más a los demás de lo que ellos me quieren.',
                'label_fr' => "En général, j'aime les autres plus qu'ils ne m'aiment.",
                'label_it' => 'In generale, amo gli altri più di quanto loro mi amino.',
                'mode' => 'backward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question38_answer_id',
            ],
            [
                'label' => 'Family illnesses cannot be avoided.',
                'label_pl' => 'Choroby rodzinne nie mogą być uniknięte.',
                'label_de' => 'Familienerkrankungen können nicht vermieden werden.',
                'label_pt' => 'As doenças familiares não podem ser evitadas.',
                'label_es' => 'Las enfermedades familiares no se pueden evitar.',
                'label_fr' => 'Les maladies familiales ne peuvent être évitées.',
                'label_it' => 'Le malattie familiari non possono essere evitate.',
                'mode' => 'backward',
                'factor1' => 'Health',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question39_answer_id',
            ],
            [
                'label' => 'As I grow older, I notice my patience is increasing.',
                'label_pl' => 'Im starszy się staję, tym bardziej zauważam, że rośnie moja cierpliwość.',
                'label_de' => 'Wenn ich älter werde, bemerke ich, dass meine Geduld zunimmt.',
                'label_pt' => 'À medida que envelheço, percebo que minha paciência está aumentando.',
                'label_es' => 'A medida que envejezco, noto que mi paciencia aumenta.',
                'label_fr' => 'En vieillissant, je remarque que ma patience augmente.',
                'label_it' => 'Man mano che invecchio, noto che la mia pazienza aumenta.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Generosity',
                'answers_ref_column' => 'question40_answer_id',
            ],
            [
                'label' => 'I enjoy knowing intelligent people.',
                'label_pl' => 'Lubię poznawać inteligentnych ludzi.',
                'label_de' => 'Es macht mir Freude, intelligente Menschen kennenzulernen.',
                'label_pt' => 'Gosto de conhecer pessoas inteligentes.',
                'label_es' => 'Disfruto conocer a personas inteligentes.',
                'label_fr' => "J'apprécie de connaître des gens intelligents.",
                'label_it' => 'Mi piace conoscere persone intelligenti.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question41_answer_id',
            ],
            [
                'label' => 'I avoid making mistakes for fear others may think I am not as good as they
                see me.',
                'label_pl' => 'Unikam popełniania błędów z obawy, że inni mogą sądzić, że nie jestem tak dobry, jak mnie widzą.',
                'label_de' => 'Ich vermeide es, Fehler zu machen, aus Angst, dass andere denken könnten, dass ich nicht so gut bin, wie sie mich sehen.',
                'label_pt' => 'Evito cometer erros com medo de que os outros possam pensar que não sou tão bom quanto me veem.',
                'label_es' => 'Evito cometer errores por miedo a que los demás piensen que no soy tan bueno como me ven.',
                'label_fr' => "J'évite de faire des erreurs de peur que les autres pensent que je ne suis pas aussi bon qu'ils le pensent.",
                'label_it' => 'Evito di commettere errori per paura che gli altri possano pensare che non sono così bravo come mi vedono.',
                'mode' => 'backward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question42_answer_id',
            ],
            [
                'label' => 'Volunteering to help others is difficult.',
                'label_pl' => 'Wolontariat w celu pomocy innym jest trudny.',
                'label_de' => 'Freiwilligenarbeit zur Hilfe anderer ist schwierig.',
                'label_pt' => 'Ser voluntário para ajudar os outros é difícil.',
                'label_es' => 'El voluntariado para ayudar a los demás es difícil.',
                'label_fr' => 'Le volontariat pour aider les autres est difficile.',
                'label_it' => 'Il volontariato per aiutare gli altri è difficile.',
                'mode' => 'backward',
                'factor1' => 'Health',
                'factor2' => 'Generosity',
                'answers_ref_column' => 'question43_answer_id',
            ],
            [
                'label' => 'My family and friends think I want too much out of life.',
                'label_pl' => 'Moja rodzina i przyjaciele uważają, że chcę zbyt wiele z życia.',
                'label_de' => 'Meine Familie und Freunde denken, dass ich zu viel vom Leben will.',
                'label_pt' => 'Minha família e amigos acham que eu quero muito da vida.',
                'label_es' => 'Mi familia y amigos piensan que quiero demasiado de la vida.',
                'label_fr' => 'Ma famille et mes amis pensent que je demande trop de la vie.',
                'label_it' => 'La mia famiglia e i miei amici pensano che voglia troppo dalla vita.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question44_answer_id',
            ],
            [
                'label' => 'I am in control of my life.',
                'label_pl' => 'Kontroluję swoje życie.',
                'label_de' => 'Ich habe mein Leben im Griff.',
                'label_pt' => 'Estou no controle da minha vida.',
                'label_es' => 'Tengo el control de mi vida.',
                'label_fr' => 'Je contrôle ma vie.',
                'label_it' => 'Ho il controllo della mia vita.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question45_answer_id',

            ],
            [
                'label' => 'When I am criticized it bring back bad memories from childhood.',
                'label_pl' => 'Kiedy jestem krytykowany, przywołuje to złe wspomnienia z dzieciństwa.',
                'label_de' => 'Wenn ich kritisiert werde, werden schlechte Erinnerungen aus der Kindheit wach.',
                'label_pt' => 'Quando sou criticado, traz de volta más lembranças da infância.',
                'label_es' => 'Cuando me critican, me traen malos recuerdos de la infancia.',
                'label_fr' => "Quand je suis critiqué, cela ramène de mauvais souvenirs d'enfance.",
                'label_it' => "Quando vengo criticato, riporta brutti ricordi dell'infanzia.",
                'mode' => 'backward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question46_answer_id',
            ],
            [
                'label' => 'I have more difficulty letting go of what makes me angry now than when I was
                younger.',
                'label_pl' => 'Teraz trudniej mi jest porzucić to, co mnie wkurza, niż kiedy byłem młodszy.',
                'label_de' => 'Es fällt mir jetzt schwerer, das loszulassen, was mich wütend macht, als wenn ich jünger war.',
                'label_pt' => 'Tenho mais dificuldade em deixar de lado o que me deixa irritado agora do que quando era mais jovem.',
                'label_es' => 'Me cuesta más dejar lo que me enoja ahora que cuando era más joven.',
                'label_fr' => "J'ai plus de mal à laisser partir ce qui me met en colère maintenant qu'avant quand j'étais plus jeune.",
                'label_it' => 'Ora mi è più difficile lasciare andare ciò che mi fa arrabbiare rispetto a quando ero più giovane.',
                'mode' => 'backward',
                'factor1' => 'Aging',
                'factor2' => 'Generosity',
                'answers_ref_column' => 'question47_answer_id',
            ],
            [
                'label' => 'I feel embarrassed when people compliment me in public.',
                'label_pl' => 'Czuję się zakłopotany, gdy ludzie mnie chwalą publicznie.',
                'label_de' => 'Ich fühle mich peinlich berührt, wenn mich Leute öffentlich loben.',
                'label_pt' => 'Sinto-me envergonhado quando as pessoas me elogiam em público.',
                'label_es' => 'Me siento avergonzado cuando la gente me elogia en público.',
                'label_fr' => 'Je me sens gêné quand les gens me complimentent en public.',
                'label_it' => 'Mi sento imbarazzato quando la gente mi fa complimenti in pubblico.',
                'mode' => 'backward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question48_answer_id',
            ],
            [
                'label' => 'I am better at solving other people’s problems than my own.',
                'label_pl' => 'Lepiej radzę sobie z rozwiązywaniem problemów innych osób niż swoich własnych.',
                'label_de' => 'Ich bin besser darin, die Probleme anderer zu lösen als meine eigenen.',
                'label_pt' => 'Sou melhor em resolver os problemas dos outros do que os meus próprios.',
                'label_es' => 'Soy mejor resolviendo los problemas de los demás que los míos propios.',
                'label_fr' => 'Je suis meilleur pour résoudre les problèmes des autres que les miens.',
                'label_it' => 'Sono migliore nel risolvere i problemi degli altri che i miei.',
                'mode' => 'backward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question49_answer_id',
            ],
            [
                'label' => 'I love myself.',
                'label_pl' => 'Kocham siebie.',
                'label_de' => 'Ich liebe mich selbst.',
                'label_pt' => 'Eu me amo.',
                'label_es' => 'Me amo a mí mismo.',
                'label_fr' => "Je m'aime.",
                'label_it' => 'Mi amo.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question50_answer_id',
            ],
            [
                'label' => 'Aging is affecting my mental and physical abilities.',
                'label_pl' => 'Starzenie się wpływa na moje zdolności umysłowe i fizyczne.',
                'label_de' => 'Das Altern beeinträchtigt meine geistigen und körperlichen Fähigkeiten.',
                'label_pt' => 'O envelhecimento está afetando minhas habilidades mentais e físicas.',
                'label_es' => 'El envejecimiento está afectando mis habilidades mentales y físicas.',
                'label_fr' => 'Le vieillissement affecte mes capacités mentales et physiques.',
                'label_it' => "L'invecchiamento sta influenzando le mie capacità mentali e fisiche.",
                'mode' => 'backward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question51_answer_id',
            ],
            [
                'label' => 'My past does not allow me to enjoy times of good fortune in my life.',
                'label_pl' => 'Moja przeszłość nie pozwala mi cieszyć się czasami szczęśliwego losu w moim życiu.',
                'label_de' => 'Meine Vergangenheit lässt mich keine Zeiten des Glücks in meinem Leben genießen.',
                'label_pt' => 'Meu passado não me permite desfrutar dos momentos de boa sorte na minha vida.',
                'label_es' => 'Mi pasado no me permite disfrutar de los momentos de buena fortuna en mi vida.',
                'label_fr' => 'Mon passé ne me permet pas de profiter des moments de bonne fortune dans ma vie.',
                'label_it' => 'Il mio passato non mi permette di godermi i momenti di buona fortuna nella mia vita.',
                'mode' => 'backward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question52_answer_id',
            ],
            [
                'label' => 'I enjoy when others give me attention at gatherings.',
                'label_pl' => 'Lubię, gdy inni zwracają na mnie uwagę na spotkaniach.',
                'label_de' => 'Ich genieße es, wenn andere mir Aufmerksamkeit bei Treffen schenken.',
                'label_pt' => 'Gosto quando os outros me dão atenção em encontros.',
                'label_es' => 'Disfruto cuando otros me prestan atención en reuniones.',
                'label_fr' => "J'apprécie quand les autres me donnent de l'attention lors de rassemblements.",
                'label_it' => 'Mi piace quando gli altri mi prestano attenzione durante gli incontri.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question53_answer_id',
            ],
            [
                'label' => 'I approach life challenges with confidence in my creativity.',
                'label_pl' => 'Podchodzę do życiowych wyzwań z pewnością siebie w mojej kreatywności.',
                'label_de' => 'Ich gehe Lebensherausforderungen mit Vertrauen in meine Kreativität an.',
                'label_pt' => 'Abordo os desafios da vida com confiança na minha criatividade.',
                'label_es' => 'Afronto los desafíos de la vida con confianza en mi creatividad.',
                'label_fr' => "J'aborde les défis de la vie avec confiance en ma créativité.",
                'label_it' => 'Affronto le sfide della vita con fiducia nella mia creatività.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question54_answer_id',
            ],
            [
                'label' => 'I am a lucky person.',
                'label_pl' => 'Jestem szczęśliwym człowiekiem.',
                'label_de' => 'Ich bin ein glücklicher Mensch.',
                'label_pt' => 'Sou uma pessoa sortuda.',
                'label_es' => 'Soy una persona afortunada.',
                'label_fr' => 'Je suis une personne chanceuse.',
                'label_it' => 'Sono una persona fortunata.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Gratitude',
                'answers_ref_column' => 'question55_answer_id',
            ],
            [
                'label' => 'I am more accomplished than my parents.',
                'label_pl' => 'Osiągnąłem więcej niż moi rodzice.',
                'label_de' => 'Ich bin erfolgreicher als meine Eltern.',
                'label_pt' => 'Sou mais realizado do que meus pais.',
                'label_es' => 'Estoy más realizado que mis padres.',
                'label_fr' => 'Je suis plus accompli que mes parents.',
                'label_it' => 'Sono più realizzato dei miei genitori.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question56_answer_id',
            ],
            [
                'label' => 'I have as much energy as I did when I was younger.',
                'label_pl' => 'Mam tyle samo energii, co kiedyś, gdy byłem młodszy.',
                'label_de' => 'Ich habe genauso viel Energie wie früher.',
                'label_pt' => 'Tenho tanta energia quanto tinha quando era mais jovem.',
                'label_es' => 'Tengo tanta energía como cuando era más joven.',
                'label_fr' => "J'ai autant d'énergie que lorsque j'étais plus jeune.",
                'label_it' => 'Ho tanta energia quanto avevo quando ero più giovane.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question57_answer_id',
            ],
            [
                'label' => 'I feel comfortable being myself around strangers.',
                'label_pl' => 'Czuję się komfortowo będąc sobą wobec obcych.',
                'label_de' => 'Ich fühle mich wohl, wenn ich bei Fremden ich selbst bin.',
                'label_pt' => 'Sinto-me confortável sendo eu mesmo com estranhos.',
                'label_es' => 'Me siento cómodo siendo yo mismo con desconocidos.',
                'label_fr' => "Je me sens à l'aise en étant moi-même avec des étrangers.",
                'label_it' => 'Mi sento a mio agio essendo me stesso con gli sconosciuti.',
                'mode' => 'forward',
                'factor1' => 'Self-Valuation',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question58_answer_id',
            ],
            [
                'label' => 'I frequently feel I have to rush whatever I am doing for lack of time.',
                'label_pl' => 'Często mam wrażenie, że muszę spieszyć się z tym, co robię z braku czasu.',
                'label_de' => 'Ich habe oft das Gefühl, dass ich mich wegen Zeitmangels beeilen muss, egal was ich tue.',
                'label_pt' => 'Frequentemente sinto que tenho que me apressar com o que estou fazendo por falta de tempo.',
                'label_es' => 'A menudo siento que tengo que darme prisa en lo que estoy haciendo por falta de tiempo.',
                'label_fr' => "J'ai souvent l'impression de devoir me dépêcher dans ce que je fais par manque de temps.",
                'label_it' => 'Spesso mi sento costretto a fretta qualunque cosa faccia per mancanza di tempo.',
                'mode' => 'backward',
                'factor1' => 'Time',
                'factor2' => 'Curiosity',
                'answers_ref_column' => 'question59_answer_id',
            ],
            [
                'label' => 'I am wiser now than ever before.',
                'label_pl' => 'Jestem teraz mądrzejszy niż kiedykolwiek wcześniej.',
                'label_de' => 'Ich bin jetzt weiser als je zuvor.',
                'label_pt' => 'Estou mais sábio agora do que nunca.',
                'label_es' => 'Ahora soy más sabio que nunca.',
                'label_fr' => 'Je suis plus sage maintenant que jamais.',
                'label_it' => 'Sono più saggio ora che mai prima.',
                'mode' => 'forward',
                'factor1' => 'Aging',
                'factor2' => 'Admiration',
                'answers_ref_column' => 'question60_answer_id',
            ],
        ];

        $factors = Factor::pluck('id', 'name')->toArray();

        foreach ($questions as $question) {
            $question['factor1_id'] = $factors[$question['factor1']];
            $question['factor2_id'] = $factors[$question['factor2']];
            unset($question['factor1'], $question['factor2']);

            Question::create($question);
        }
    }
}
